### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by adamsondelacruz** [vmware/pyvmomi-community-samples#155]
An error is thrown when trying to connect to venture.

Environment: Ubuntu 14.04
tried both on python 2.7.6 and 3.4
using pip install --upgrade pyvmomi 

Here is the code:

import atexit
from pyVim import connect
from pyVmomi import vmodl
service_instance = connect.SmartConnect(host="hostname",user="username",pwd="****")

and here is the error:
/home/adam/pythonProjects/vmwenv27/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/adam/pythonProjects/vmwenv27/local/lib/python2.7/site-packages/pyVim/connect.py", line 590, in SmartConnect
    path=path)
  File "/home/adam/pythonProjects/vmwenv27/local/lib/python2.7/site-packages/pyVim/connect.py", line 234, in Connect
    keyFile, certFile)
  File "/home/adam/pythonProjects/vmwenv27/local/lib/python2.7/site-packages/pyVim/connect.py", line 333, in __Login
    x = content.sessionManager.Login(user, pwd, None)
  File "/home/adam/pythonProjects/vmwenv27/local/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 566, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/home/adam/pythonProjects/vmwenv27/local/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 375, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "/home/adam/pythonProjects/vmwenv27/local/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py", line 1301, in InvokeMethod
    raise obj # pylint: disable-msg=E0702
pyVmomi.VmomiSupport.InvalidRequest: (vmodl.fault.InvalidRequest) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = '\nError returned by expat parser: not well-formed (invalid token)\n\nwhile parsing serialized value of type string\nat line 3, column 90\n\nwhile parsing call information for method Login\nat line 3, column 14\n\nwhile parsing SOAP body\nat line 3, column 0\n\nwhile parsing SOAP envelope\nat line 2, column 0\n\nwhile parsing HTTP request for method login\non object of type vim.SessionManager\nat line 1, column 0',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) []
}

**Comment by Akasurde** [comment]
@adamsondelacruz What is username and password ? Are you passing any non-ascii characters in username and password ? Also, check if there is '/' in username ?

**Comment by vaidehi8goliwar** [comment]
i had same error but while executing a powershell script in vm using execute_a_program.py,
do u have solution for this error

**Comment by MeirPeleg** [comment]
Hi, 

I also encounter it on my ansible server, any solutions?
