### ISSUE TITLE
AttributeError: 'vim.Folder' object has no attribute 'resourcePool'

### ISSUE THREAD

**Issue by Sispheor** [vmware/pyvmomi-community-samples#201]
My error
```
Traceback (most recent call last):
  File "pyvmomi-community-samples/samples/create_vm.py", line 108, in <module>
    main()
  File "pyvmomi-community-samples/samples/create_vm.py", line 100, in main
    resource_pool = hosts[0].resourcePool
AttributeError: 'vim.Folder' object has no attribute 'resourcePool'
```

I'm trying to create a simple VM. Here is my code
```
def create_vm(name, service_instance, vm_folder, resource_pool, datastore):
    vm_name = name
    datastore_path = '[' + datastore + '] ' + vm_name

    # bare minimum VM shell, no disks. Feel free to edit
    vmx_file = vim.vm.FileInfo(logDirectory=None,
                               snapshotDirectory=None,
                               suspendDirectory=None,
                               vmPathName=datastore_path)

    config = vim.vm.ConfigSpec(name=vm_name, memoryMB=128, numCPUs=1,
                               files=vmx_file, guestId='dosGuest',
                               version='vmx-08')

    print "Creating VM {}...".format(vm_name)
    task = vm_folder.CreateVM_Task(config=config, pool=resource_pool)
    tasks.wait_for_tasks(service_instance, [task])


def main():
    """
    Simple command-line program for listing the virtual machines on a system.
    """

    args = get_args()
    service_instance = connect.SmartConnect(host=args.host,
                                            user=args.user,
                                            pwd=args.password,
                                            port=int(args.port))

    if not service_instance:
        print("Could not connect to the specified host using specified "
              "username and password")
        return -1

    atexit.register(connect.Disconnect, service_instance)

    name = "test_vm"
    content = service_instance.RetrieveContent()
    datacenter = content.rootFolder.childEntity[0]
    vm_folder = datacenter.vmFolder
    hosts = datacenter.hostFolder.childEntity
    resource_pool = hosts[0].resourcePool
    datastore = "L_on_helios41"

    create_vm(name, service_instance, vm_folder, resource_pool, datastore)
    return 0
```

BTW PyCharm is telling me that the vim import cannot be resolved. But if I trust this post (https://github.com/vmware/pyvmomi-community-samples/issues/49) I can ignore the missing reference. Right?

**Comment by Sispheor** [comment]
It's ok. It was not the good object to work with. I used the search function before to get my resource_pool.
