### ISSUE TITLE
The simplest example does not run

### ISSUE THREAD

**Issue by wangsuyi640** [vmware/pyvmomi-community-samples#244]
I just install the pyvmomi using "pip install pyvmomi" and run the  simplest example, and failed:

susu@susu-web:~/vmware-pyvmomi-sample/samples$ python getallvms.py --host 192.168.3.96 --port 443 --user root --password vmware
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "getallvms.py", line 97, in <module>
    main()
  File "getallvms.py", line 73, in main
    port=int(args.port))
  File "/usr/local/lib/python2.7/dist-packages/pyVim/connect.py", line 663, in SmartConnect
    sslContext)
  File "/usr/local/lib/python2.7/dist-packages/pyVim/connect.py", line 552, in __FindSupportedVersion
    sslContext)
  File "/usr/local/lib/python2.7/dist-packages/pyVim/connect.py", line 472, in __GetServiceVersionDescription
    tree = __GetElementTreeFromUrl(url, sslContext)
  File "/usr/local/lib/python2.7/dist-packages/pyVim/connect.py", line 440, in __GetElementTreeFromUrl
    sock = requests.get(url)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 447, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

192.168.3.96: my vcenter 5.5 base on suse linux
root: the default username
vmware: the default passwod
443: the default port

However, things go wrong, what is the problem?

**Comment by wangsuyi640** [comment]
use pyvmomi ==5.5 with fix the issue.
