### ISSUE TITLE
Installing requirements.txt results in error

### ISSUE THREAD

**Issue by perrin4869** [vmware/pyvmomi-community-samples#281]
I'm running Arch Linux, Python `3.5.2`. Trying to install the requirements results in the following:

``` bash
$ virtualenv venv
$ . venv/bin/activate
$ pip install -r requirements.txt
Collecting argparse (from -r requirements.txt (line 1))
  Using cached argparse-1.4.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): pyvmomi>=5.5.0.2014.1.1 in /usr/lib/python3.5/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/lib/python3.5/site-packages (from -r requirements.txt (line 3))
Collecting suds<0.7,>=0.4 (from -r requirements.txt (line 4))
  Using cached suds-0.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-d1gt5zau/suds/setup.py", line 20, in <module>
        import suds
      File "/tmp/pip-build-d1gt5zau/suds/suds/__init__.py", line 154, in <module>
        import client
    ImportError: No module named 'client'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-d1gt5zau/suds/
```

**Comment by perrin4869** [comment]
Maybe consider changing `suds` for `suds-jurko` in `requirements.txt`? Not sure if that will necessitate more changes though.

**Comment by GhostofGoes** [comment]
Having the same issue...
