### ISSUE TITLE
Unable to register SCSI device and add disk to one existing VM

### ISSUE THREAD

**Issue by tonardo2015** [vmware/pyvmomi-community-samples#282]
Hi guys,

Can you help have a look at our code, we cannot add disk to one existing VM, it report error "The device '0' is referring to a non-existing controller '0'", looks like there is some problem with the SCSI controller, but I've done what is suggest in the example. Anything else is missing? Thanks a lot for your kind help!

def get_obj(content, vimtype, name):
    obj = None
    container = content.viewManager.CreateContainerView(content.rootFolder, vimtype, True)
    for c in container.view:
        if c.name == name:
            obj = c
            break
    return obj

def add_scsi_device_to_vm(vm_obj):
    spec = vim.vm.ConfigSpec()
    scsi_ctr = vim.vm.device.VirtualDeviceSpec()
    scsi_ctr.operation = vim.vm.device.VirtualDeviceSpec.Operation.add
    scsi_ctr.device = vim.vm.device.VirtualLsiLogicController()
    scsi_ctr.device.deviceInfo = vim.Description()
    scsi_ctr.device.slotInfo = vim.vm.device.VirtualDevice.PciBusSlotInfo()
    scsi_ctr.device.slotInfo.pciSlotNumber = 16
    scsi_ctr.device.controllerKey = 100
    scsi_ctr.device.unitNumber = 3
    scsi_ctr.device.busNumber = 0
    scsi_ctr.device.hotAddRemove = True
    scsi_ctr.device.sharedBus = 'noSharing'
    scsi_ctr.device.scsiCtlrUnitNumber = 7

    vm_obj.ReconfigVM_Task(spec=spec)
    print "SCSI device added to %s" % (vm_obj.config.name)
    return scsi_ctr

def add_disk_to_vm(vm_obj, disk_size, disk_type):
    """
    add disk to a virtual machine
    :param vm_obj: virtual machine object
    :param disk_size: disk size in gb
    :param disk_type: thin or persistent
    :return: if the operation succeeds return 0, else return -1
    """
    print "Virtual Machine Object......: %s" % vm_obj
    print "New disk size in KB......: %s" % disk_size
    print "New disk type......: %s" % disk_type

    spec = vim.vm.ConfigSpec()

    scsi_ctr = add_scsi_device_to_vm(vm_obj)
    controller = scsi_ctr.device

    # get all disks on a VM, set unit_number to the next available
    for device in vm_obj.config.hardware.device:
        unit_number = 3
        if  hasattr(device.backing, 'fileName'):
            unit_number = int(device.unitNumber) + 1
            # unit_number 7 is reserved for scsi controller
            if unit_number == 7:
                unit_number += 1
            if unit_number >= 16:
                print "disk number exceeds the maximum supported value (16)"
                return -1
        if isinstance(device, vim.vm.device.VirtualSCSIController):
            controller = device
            print "controller is %s, controller.device is %s" % (controller, controller.device)

    # add disk here
    device_changes = []
    new_disk_gb = int(disk_size) * 1024 * 1024
    disk_spec = vim.vm.device.VirtualDeviceSpec()
    disk_spec.fileOperation = "create"
    disk_spec.operation = vim.vm.device.VirtualDeviceSpec.Operation.add
    disk_spec.device = vim.vm.device.VirtualDisk()
    disk_spec.device.backing = vim.vm.device.VirtualDisk.FlatVer2BackingInfo()
    if disk_type == 'thin':
        disk_spec.device.backing.thinProvisioned = True
    disk_spec.device.backing.diskMode = 'persistent'
    disk_spec.device.unitNumber = len(controller.device)
    disk_spec.device.capacityInKB = new_disk_gb
    disk_spec.device.controllerKey = controller.key
    device_changes.append(disk_spec)
    spec.deviceChange = device_changes
    vm_obj.ReconfigVM_Task(spec=spec)
    print "%sGB disk added to %s" % (disk_size, vm_obj.config.name)
    return 0

try:
    import ssl
    context = ssl.SSLContext(ssl.PROTOCOL_SSLv23)
    context.verify_mode = ssl.CERT_NONE

    service_instance = connect.SmartConnect(host=url,
                                            user=username,
                                            pwd=password,
                                            port=int(443),
                                            sslContext=context)
except Exception as exc:
    print exc

content = service_instance.RetrieveContent()

vm_obj = get_obj(content, [vim.VirtualMachine], 'CycloneVirtualMachineTest')
print "vm_obj: %s" % (vm_obj)
add_scsi_device_to_vm(vm_obj)
add_disk_to_vm(vm_obj, 50, 'thin')

**Comment by prziborowski** [comment]
I think for the scsi controller, you don't need to hook it up to a controller as well (it might plug into a pci controller, but I think that may happen automatically if you don't try to configure it).

So I'd suggest try removing:
```
scsi_ctr.device.slotInfo = vim.vm.device.VirtualDevice.PciBusSlotInfo()
scsi_ctr.device.slotInfo.pciSlotNumber = 16
scsi_ctr.device.controllerKey = 100
```
Or at a minimum try removing scsi_ctr.device.controllerKey.

Besides that it should work.
Note that if you have 7 disks on the controller that this line will get you:
disk_spec.device.unitNumber = len(controller.device)
but you can worry about that later.

**Comment by tonardo2015** [comment]
Thanks @prziborowski, I tried, your suggestion, but the issue is still there.

**Comment by prziborowski** [comment]
Sorry, I completely missed something and didn't notice it until trying out your script!

In your add_scsi_device_to_vm function, you aren't putting the scsi_ctr into the spec.
You should add something like:
   spec.deviceChange = [scsi_ctr]

Also the reconfigure tasks are asynchronous, so you should use pyVim.task.WaitForTask on them:

from pyVim.task import WaitForTask
WaitForTask(vm_obj.ReconfigVM_Task(spec=spec))

Otherwise it might be possibly the add_scsi_device_to_vm's reconfigure is still running when add_disk_to_vm is searching the config.

**Comment by tonardo2015** [comment]
Thanks @prziborowski, sorry for late reply.

I've updated the code as your suggestion, below error happened:

Traceback (most recent call last):
  File "/home/cyc/project/stack/test/cyclone_vasa.py", line 329, in <module>
    exit(main())
  File "/home/cyc/project/stack/test/cyclone_vasa.py", line 295, in main
    vsphere.add_disk_to_vm(vm_obj, 20, 'persistent')
  File "/home/cyc/project/stack/test/utilities/vsphere.py", line 891, in add_disk_to_vm
    WaitForTask(vm_obj.ReconfigVM_Task(spec=spec))
  File "/home/cyc/.virtualenvs/cyc_wshark/lib/python2.7/site-packages/pyVim/task.py", line 139, in WaitForTask
    raise task.info.error
pyVmomi.VmomiSupport.InvalidDeviceSpec: (vim.fault.InvalidDeviceSpec) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = "Invalid configuration for device '0'.",
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   property = u'virtualDeviceSpec.device.controllerKey',
   deviceIndex = 0
}

Here is my updated code:

def add_disk_to_vm(vm_obj, disk_size, disk_type):
    """
    add disk to a virtual machine
    :param vm_obj: virtual machine object
    :param disk_size: disk size in gb
    :param disk_type: thin or persistent
    :return: if the operation succeeds return 0, else return -1
    TBD
    """
    LOGGER.info("Virtual Machine Object......: %s", vm_obj)
    LOGGER.info("New disk size in GB......: %s", disk_size)
    LOGGER.info("New disk type......: %s", disk_type)
    spec = vim.vm.ConfigSpec()

    scsi_ctr = add_scsi_device_to_vm(vm_obj)
    controller = scsi_ctr.device
    unit_number = 0
    # get all disks on a VM, set unit_number to the next available
    for device in vm_obj.config.hardware.device:
        if  hasattr(device.backing, 'fileName'):
            unit_number = int(device.unitNumber) + 1
            # unit_number 7 is reserved for scsi controller
            if unit_number == 7:
                unit_number += 1
            if unit_number >= 16:
                LOGGER.info("disk number exceeds the maximum supported value (16)")
                return -1
        if isinstance(device, vim.vm.device.VirtualSCSIController):
            controller = device

    if unit_number == 0:
        unit_number = 1
    # add disk here
    device_changes = []
    new_disk_gb = int(disk_size) * 1024 * 1024
    disk_spec = vim.vm.device.VirtualDeviceSpec()
    disk_spec.fileOperation = "create"
    disk_spec.operation = vim.vm.device.VirtualDeviceSpec.Operation.add
    disk_spec.device = vim.vm.device.VirtualDisk()
    disk_spec.device.backing = vim.vm.device.VirtualDisk.FlatVer2BackingInfo()
    if disk_type == 'thin':
        disk_spec.device.backing.thinProvisioned = True
    disk_spec.device.backing.diskMode = 'persistent'
    disk_spec.device.unitNumber = len(controller.device)
    disk_spec.device.capacityInKB = new_disk_gb
    #disk_spec.device.controllerKey = controller.key
    device_changes.append(disk_spec)
    spec.deviceChange = device_changes
    WaitForTask(vm_obj.ReconfigVM_Task(spec=spec))
    LOGGER.info("%sGB disk added to %s", disk_size, vm_obj.config.name)
    return 0

def add_scsi_device_to_vm(vm_obj):
    """
    add scsi device to a virtual machine
    :param vm_obj: virtual machine object
    :return: scsi configuration
    :TBD
    """
    spec = vim.vm.ConfigSpec()
    scsi_ctr = vim.vm.device.VirtualDeviceSpec()
    scsi_ctr.operation = vim.vm.device.VirtualDeviceSpec.Operation.add
    scsi_ctr.device = vim.vm.device.VirtualLsiLogicController()
    scsi_ctr.device.deviceInfo = vim.Description()
    #scsi_ctr.device.slotInfo = vim.vm.device.VirtualDevice.PciBusSlotInfo()
    #scsi_ctr.device.slotInfo.pciSlotNumber = 16
    #scsi_ctr.device.controllerKey = 100
    scsi_ctr.device.unitNumber = 3
    scsi_ctr.device.busNumber = 0
    scsi_ctr.device.hotAddRemove = True
    scsi_ctr.device.sharedBus = 'noSharing'
    scsi_ctr.device.scsiCtlrUnitNumber = 7

    spec.deviceChange = [scsi_ctr]

    WaitForTask(vm_obj.ReconfigVM_Task(spec=spec))
    LOGGER.info("SCSI device added to %s", vm_obj.config.name)
    return scsi_ctr

Do you have any thoughts? Thanks a lot!

**Comment by prziborowski** [comment]
For the disk, you should keep this line in (uncommented):
disk_spec.device.controllerKey = controller.key

The error in add_disk_to_vm is hinting toward that:
property = u'virtualDeviceSpec.device.controllerKey

**Comment by tonardo2015** [comment]
@prziborowski Thanks this issue is solved with your suggestion!

**Comment by kasturinarra** [comment]
Thanks, my issue is resolved as well after using this line in my code.
disk_spec.device.unitNumber = len(controller.device)

Below is the code which works for me.

# get all disks on a VM, set unit_number to the next available
        for dev in vm[0].config.hardware.device:
            g.log.info("dev is %s" % dev)
            if hasattr(dev.backing, 'fileName'):
                unit_number = int(dev.unitNumber) + 1
                g.log.info("unit_number is %s" % dev.unitNumber)
                if unit_number == 7:
                    unit_number += 1
                if unit_number >= 16:
                    g.log.info("We do not support these many disks")
                    return
            if isinstance(dev, vim.vm.device.VirtualSCSIController):
                controller = dev

        # Add disk to vm
        dev_changes = []
        new_disk_gb = int(disk_size) * 1024 * 1024
        virtual_hdd_spec = vim.vm.device.VirtualDeviceSpec()
        virtual_hdd_spec.fileOperation = "create"
        virtual_hdd_spec.operation = (
            vim.vm.device.VirtualDeviceSpec.Operation.add)
        virtual_hdd_spec.device = vim.vm.device.VirtualDisk()
        virtual_hdd_spec.device.backing = (
            vim.vm.device.VirtualDisk.FlatVer2BackingInfo())
        g.log.info("disk type is %s" % disk_type)
        if disk_type == 'thin':
            virtual_hdd_spec.device.backing.thinProvisioned = True
        virtual_hdd_spec.device.backing.diskMode = 'persistent'
        virtual_hdd_spec.device.unitNumber = len(controller.device)
        virtual_hdd_spec.device.capacityInKB = new_disk_gb
        virtual_hdd_spec.device.controllerKey = controller.key
        dev_changes.append(virtual_hdd_spec)

        # wait for the task to complete
        spec = vim.vm.ConfigSpec()
        spec.deviceChange = dev_changes
        task = vm[0].ReconfigVM_Task(spec=spec)
        self._wait_for_tasks([task], self.vsphere_client)
