### ISSUE TITLE
socket.gaierror: [Errno 11001] getaddrinfo failed

### ISSUE THREAD

**Issue by markchuman** [vmware/pyvmomi-community-samples#331]
Getting the below error on numerous samples.  add_vswitch_to_host.py and dc_create.py that I've tried.  Others (vcenter_details.py for example) work fine.  Tried to add ssl.SSLContext, but no good.  Full error:

Traceback (most recent call last):
  File "dc_create.py", line 39, in <module>
    sslContext= context)
  File "c:\python33\lib\site-packages\pyVim\connect.py", line 817, in SmartConnect
    sslContext)
  File "c:\python33\lib\site-packages\pyVim\connect.py", line 702, in __FindSupportedVersion
    sslContext)
  File "c:\python33\lib\site-packages\pyVim\connect.py", line 622, in __GetServiceVersionDescription
    path + "/vimServiceVersions.xml", sslContext)
  File "c:\python33\lib\site-packages\pyVim\connect.py", line 588, in __GetElementTree
    conn.request("GET", path)
  File "c:\python33\lib\http\client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "c:\python33\lib\http\client.py", line 1151, in _send_request
    self.endheaders(body)
  File "c:\python33\lib\http\client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "c:\python33\lib\http\client.py", line 934, in _send_output
    self.send(msg)
  File "c:\python33\lib\http\client.py", line 877, in send
    self.connect()
  File "c:\python33\lib\http\client.py", line 1252, in connect
    super().connect()
  File "c:\python33\lib\http\client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "c:\python33\lib\socket.py", line 693, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "c:\python33\lib\socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

**Comment by blacksponge** [comment]
The only times I have got the error I mistyped the host. I have just tested `add_vswitch_to_host.py` and I didn't have any problem to perform the connection. Are you sure that the host was reachable and that you didn't mistype it ?

**Comment by akhilesh-agrhari** [comment]
I am having the same error. Can you please suggest m a correct host

**Comment by blacksponge** [comment]
@akhilesh-agrhari sorry but that was quite a while ago and I don't have the possibilty of doing any kind of test now. I would say an ip or valid domain name.

**Comment by bill-rheda** [comment]
I have the same error and i can assure you that my host name and port is correct. What can i do about this please?

**Comment by Naman-Biswajit** [comment]
- SDADAS
ASDADAS

**Comment by funny000** [comment]
Traceback (most recent call last):
  File "D:/Propy/pythonProject_douyu/douyu.py", line 267, in <module>
    client = DouyuClient('openbarrage.douyutv.com',8601,data_callback=data_callback)
  File "D:/Propy/pythonProject_douyu/douyu.py", line 132, in __init__
    self.connect(address)
  File "C:\Users\adain\AppData\Local\Programs\Python\Python37\lib\asyncore.py", line 333, in connect
    err = self.socket.connect_ex(address)
socket.gaierror: [Errno 11001] getaddrinfo failed

**Comment by funny000** [comment]
Have anypeopel solve the problem?

**Comment by markdibe** [comment]
I am encountering the same issue 
Traceback (most recent call last):
  File "/app/EmailSender/main.py", line 9, in <module>
    EmailSender(push_file_path=__path).send_message()
  File "/app/EmailSender/EmailSender.py", line 25, in send_message
    Email_Auth(push_mail=config, path_file=path_file).send_mail(file_names=files)
  File "/app/EmailSender/EmailSender.py", line 79, in send_mail
    self.generate_smtp(msg)
  File "/app/EmailSender/EmailSender.py", line 103, in generate_smtp
    smtp = smtplib.SMTP(self.server, self.port)
  File "/usr/local/lib/python3.9/smtplib.py", line 253, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.9/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.9/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.9/socket.py", line 822, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

**Comment by avinkr** [comment]
Traceback (most recent call last):
  File "C:\Users\lenovo\Desktop\Keylogger\keylogger.py", line 124, in <module>
    keylogger.run()
  File "C:\Users\lenovo\Desktop\Keylogger\keylogger.py", line 94, in run
    self.report()
  File "C:\Users\lenovo\Desktop\Keylogger\keylogger.py", line 57, in report
    self.send_mail(self.email, self.password, "\n\n" + self.log)
  File "C:\Users\lenovo\Desktop\Keylogger\keylogger.py", line 50, in send_mail
    server = smtplib.SMTP('smtp.gmail.com', 587, message.encode("utf8"))
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python39\lib\smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python39\lib\smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python39\lib\smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python39\lib\socket.py", line 822, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python39\lib\socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

**Comment by barisdnmz** [comment]
Traceback (most recent call last):
  File "C:\Users\EmiHP\PycharmProjects\sftp_download\main.py", line 6, in <module>
    transport=paramiko.Transport((host,port))
  File "C:\Users\EmiHP\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 426, in __init__
    addrinfos = socket.getaddrinfo(
  File "C:\Users\EmiHP\AppData\Local\Programs\Python\Python39\lib\socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

**Comment by barisdnmz** [comment]
make sure that the hostname is just hostname and not including any path in the hostname variable, that fixed my problem.
