### ISSUE TITLE
python ssl error while trying getallvms.py

### ISSUE THREAD

**Issue by thinksabin** [vmware/pyvmomi-community-samples#359]
Hi,
I think i missed something here. I am trying to use getallvms.py and im using following command

$python getallvms.py -s 192.168.2.11 -o 443 -u test -p test

192.168.2.11 is my esxi machine not vcenter. Is this a right usage of the script???
Thanks in advance

The issues is :

Traceback (most recent call last):
  File "getallvms.py", line 97, in <module>
    main()
  File "getallvms.py", line 73, in main
    port=int(args.port))
  File "/usr/local/lib/python2.7/dist-packages/pyVim/connect.py", line 817, in SmartConnect
    sslContext)
  File "/usr/local/lib/python2.7/dist-packages/pyVim/connect.py", line 702, in __FindSupportedVersion
    sslContext)
  File "/usr/local/lib/python2.7/dist-packages/pyVim/connect.py", line 622, in __GetServiceVersionDescription
    path + "/vimServiceVersions.xml", sslContext)
  File "/usr/local/lib/python2.7/dist-packages/pyVim/connect.py", line 588, in __GetElementTree
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1278, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python2.7/ssl.py", line 353, in wrap_socket
    _context=self)
  File "/usr/lib/python2.7/ssl.py", line 601, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 830, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

**Comment by GhostofGoes** [comment]
What version of python 2.7 are you using? (I recall issues with versions older than 2.7.6)
Is the server's SSL certificate trusted?

**Comment by thinksabin** [comment]
Python 2.7.10

Not sure about the SSL certificate. 
Is this a right usage of the script???

$python getallvms.py -s 192.168.2.11 -o 443 -u test -p test
192.168.2.11 is my esxi machine not vcenter. 

thanks for reply

**Comment by GhostofGoes** [comment]
If you access the ESXi web interface through a browser and get a trust/certificate error, then it is not trusted. You'll need to download the certificate from the server and trust it, there are some guides out there on how to do so.

**Comment by thinksabin** [comment]
I dont think we do have trusted ssl certificate. But before that im confused about the way we have to use. Do i need to have vcenter to use this script??
currently im trying to use on esxi directly: like this
$python getallvms.py -s 192.168.2.11 -o 443 -u test -p test

If vcenter is needed then obivously usage is wrong but if its not needed, then only i can think about the issues.

thanks for reply.

**Comment by ldfsilva** [comment]
@thinksabin take a look at pull request [1], I have encountered the same issue on my environment and approached it that way to get it fixed. It basically bypasses certificate validation with option -S 

[1] pull request - https://github.com/vmware/pyvmomi-community-samples/pull/367

**Comment by thinksabin** [comment]
Thanks @ldfsilva 
-S did work for me. 
This is a great relief. :) 

thanks again.

**Comment by akshaygh1** [comment]
i applied patch but it didn't worked for me.
