### ISSUE TITLE
Initial setup error : ModuleNotFoundError: No module named 'client'

### ISSUE THREAD

**Issue by PyMeH** [vmware/pyvmomi-community-samples#399]
```
vmw@Rumens-MacBook-Pro:~/workspace/py/pyvmomi/pyvmomi-community-samples$ ../ve/bin/pip install -r requirements.txt 
Collecting argparse (from -r requirements.txt (line 1))
  Downloading argparse-1.4.0-py2.py3-none-any.whl
Requirement already satisfied: pyvmomi>=5.5.0.2014.1.1 in /Users/vmw/workspace/py/pyvmomi/ve/lib/python3.6/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: requests in /Users/vmw/workspace/py/pyvmomi/ve/lib/python3.6/site-packages (from -r requirements.txt (line 3))
Collecting suds<0.7,>=0.4 (from -r requirements.txt (line 4))
  Downloading suds-0.4.tar.gz (104kB)
    100% |████████████████████████████████| 112kB 1.4MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/5z/scglk02d39n35gbrb1jhggt80000gp/T/pip-build-k9bzytmr/suds/setup.py", line 20, in <module>
        import suds
      File "/private/var/folders/5z/scglk02d39n35gbrb1jhggt80000gp/T/pip-build-k9bzytmr/suds/suds/__init__.py", line 154, in <module>
        import client
    ModuleNotFoundError: No module named 'client'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/5z/scglk02d39n35gbrb1jhggt80000gp/T/pip-build-k9bzytmr/suds/
```

Installing client fixed the problem:

```
vmw@Rumens-MacBook-Pro:~/workspace/py/pyvmomi/pyvmomi-community-samples$ ../ve/bin/pip install client
Collecting client
  Downloading client-0.0.1.tar.gz
Building wheels for collected packages: client
  Running setup.py bdist_wheel for client ... done
  Stored in directory: /Users/vmw/Library/Caches/pip/wheels/bf/e0/f5/ce738f37f720f0a3efd2e2f5e532fa5a676c0fe9c57eb96809
Successfully built client
Installing collected packages: client
Successfully installed client-0.0.1

```

**Comment by tianhao64** [comment]
@PyMeH Thanks for reporting this. Updated the requirement.txt. It should work now.
