### ISSUE TITLE
Creating a VM without cloning

### ISSUE THREAD

**Issue by sjd69** [vmware/pyvmomi-community-samples#434]
I'm having an issue using CreateVM_Task. It always results in either BadStatusLine: '' or Remote end closed connection. 

Example code based off create random marvel sample:

```
content = self.service_instance.RetrieveContent()
        datacenter = content.rootFolder.childEntity[0]
        vm_folder = datacenter.vmFolder
        hosts = datacenter.hostFolder.childEntity
        resource_pool = hosts[0].resourcePool


        vm_name = 'VM-' + name
        datastore_path = '[' + datastore + '] ' + vm_name

        # bare minimum VM shell, no disks. Feel free to edit
        vmx_file = vim.vm.FileInfo(logDirectory=None,
                                   snapshotDirectory=None,
                                   suspendDirectory=None,
                                   vmPathName=datastore_path)

        config = vim.vm.ConfigSpec(
            name=vm_name,
            memoryMB=128,
            numCPUs=1,
            files=vmx_file,
            guestId='dosGuest',
            version='vmx-07'
        )

        print("Creating VM {}...".format(vm_name))
        task = vm_folder.CreateVM_Task(config=config, pool=resource_pool)
        tasks.wait_for_tasks(self.service_instance, [task])
```
and here's the error in python 3.6

> 
> Creating VM VM-testvm...
> Traceback (most recent call last):
>   File "C:/Users/z003he2e/Desktop/src/create_vm.py", line 188, in <module>
>     main()
>   File "C:/Users/z003he2e/Desktop/src/create_vm.py", line 182, in main
>     vc.create_vm('testvm', 'testds')
>   File "C:/Users/z003he2e/Desktop/src/create_vm.py", line 123, in create_vm
>     task = vm_folder.CreateVM_Task(config=config, pool=resource_pool)
>   File "C:\Users\z003he2e\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyVmomi\VmomiSupport.py", line 580, in <lambda>
>     self.f(*(self.args + (obj,) + args), **kwargs)
>   File "C:\Users\z003he2e\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyVmomi\VmomiSupport.py", line 386, in _InvokeMethod
>     return self._stub.InvokeMethod(self, info, args)
>   File "C:\Users\z003he2e\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyVmomi\SoapAdapter.py", line 1320, in InvokeMethod
>     resp = conn.getresponse()
>   File "C:\Users\z003he2e\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 1331, in getresponse
>     response.begin()
>   File "C:\Users\z003he2e\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 297, in begin
>     version, status, reason = self._read_status()
>   File "C:\Users\z003he2e\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 266, in _read_status
>     raise RemoteDisconnected("Remote end closed connection without"
> http.client.RemoteDisconnected: Remote end closed connection without response

And here's the traceback for python 3.4

> File "C:\Python34\lib\site-packages\pyVmomi\VmomiSupport.py", line 580, in <lambda>
>     self.f(*(self.args + (obj,) + args), **kwargs)
>   File "C:\Python34\lib\site-packages\pyVmomi\VmomiSupport.py", line 386, in _InvokeMethod
>     return self._stub.InvokeMethod(self, info, args)
>   File "C:\Python34\lib\site-packages\pyVmomi\SoapAdapter.py", line 1320, in InvokeMethod
>     resp = conn.getresponse()
>   File "C:\Python34\lib\http\client.py", line 1171, in getresponse
>     response.begin()
>   File "C:\Python34\lib\http\client.py", line 351, in begin
>     version, status, reason = self._read_status()
>   File "C:\Python34\lib\http\client.py", line 321, in _read_status
>     raise BadStatusLine(line)
> http.client.BadStatusLine: ''

Any suggestions?

**Comment by CharmingYang0** [comment]
@sjd69 
I encountered this issue today, have you solved it right now?

**Comment by pgbidkar** [comment]
> @sjd69
> I encountered this issue today, have you solved it right now?

Hi @CharmingYang0 Please can you check PR https://github.com/vmware/pyvmomi-community-samples/pull/572/files. if it solved your issue? 
It is been tested locally. 

Thanks
