### ISSUE TITLE
upload file to vm fails with 'NoneType' object has no attribute 'guest'

### ISSUE THREAD

**Issue by mindheist** [vmware/pyvmomi-community-samples#442]
# python upload_file_to_vm.py --host vcenter_name -u root -p XXXX --vm_uuid 6977ced-d0ed801c6 --vm_user root --vm_pwd XXXX -l / -f some_file.txt
Traceback (most recent call last):
  File "upload_file_to_vm.py", line 116, in <module>
    main()
  File "upload_file_to_vm.py", line 76, in main
    tools_status = vm.guest.toolsStatus
AttributeError: 'NoneType' object has no attribute 'guest'

**Comment by mindheist** [comment]
This seems to happen if the user provides the wrong the VM uuid on the command line. The "FindByUuid" function returns None when it doesn't find a valid VM corresponding to the UUID. And trying to get any vm info on "None" fails as expected.

**Comment by mindheist** [comment]
The fix for this would be exit when the VM is not found. submitting a patch shortly.
