### ISSUE TITLE
Not able to reboot VM 

### ISSUE THREAD

**Issue by akshay1909** [vmware/pyvmomi-community-samples#464]
Hi All,

I am beginner and recently started using pyvmomi module.

I tried to follow scripts available in sample folder and wrote simple script which will reboot the Virtual Machine. The code is mentioned below:-

`import atexit

from pyVim import connect

si = connect.SmartConnect(
        host="ESX-HOSTNAME",
        user="USERNAME",
        pwd="PASSWORD",
        port=443)

atexit.register(connect.Disconnect, si)
content = si.RetrieveContent()
vm = si.content.searchIndex.FindByDnsName(None, "VM-NAME",True)
if vm is None:
    print "Unable to locate VirtualMachine."
else:
     print "VM Name         : {}".format(vm.name)
     print "VM instanceUuid : {}".format(vm.config.instanceUuid)
     print "VM ipAddress    : {}".format(vm.guest.ipAddress)
     print "VM hostName     : {}".format(vm.guest.hostName)
     print "VM powerState   : {}".format(vm.runtime.powerState)
     vm.RebootGuest()
`

But when tried to execute it, I am getting following error at list line of above script
`Traceback (most recent call last):
  File "powercyle-vm.py", line 24, in <module>
    vm.RebootGuest()
  File "/apps/python/2.7.3/lib/python2.7/site-packages/pyvmomi-6.5.0.2017.5_1-py2.7.egg/pyVmomi/VmomiSupport.py", line 580, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/apps/python/2.7.3/lib/python2.7/site-packages/pyvmomi-6.5.0.2017.5_1-py2.7.egg/pyVmomi/VmomiSupport.py", line 386, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "/apps/python/2.7.3/lib/python2.7/site-packages/pyvmomi-6.5.0.2017.5_1-py2.7.egg/pyVmomi/SoapAdapter.py", line 1366, in InvokeMethod
    raise obj # pylint: disable-msg=E0702
pyVmomi.VmomiSupport.HostNotConnected: (vmodl.fault.HostNotConnected) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'Unable to communicate with the remote host, since it is disconnected.',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) []
}
`

Please let me know any suggestion/help to resolve this issue.

**Comment by sathvikm** [comment]
There is an sample script in the community-samples [reboot_vm.py](https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/reboot_vm.py)

**Comment by amard33p** [comment]
reboot_vm.py does not work if you have a self signed certificate. It will just show an error
`"Unable to connect to host with supplied info."`
You need to change this line:
```
43    try:
44        SI = connect.SmartConnect(host=ARGS.host,
```
to
```
43    try:
44        SI = connect.SmartConnectNoSSL(host=ARGS.host,
```
Even then you won't be able to reboot VMs using Name (-n) or UUID (-j) only IP Address (-i) is working right now.
Tested on pyvmomi and vSphere versions 6.7

**Comment by 1029649360** [comment]
I use Ip flag(-i), "Unable to locate VirtualMachine"  I use "python E:\python-program\pyvmomi\reboot_vm.py -s 192.168.xx.xx -u xxx -p xxx -o 443 -i 192.168.1.2" ,please
