### ISSUE TITLE
Cloining operation fails, error message states that host is in invalid state.

### ISSUE THREAD

**Issue by rmdcoding** [vmware/pyvmomi-community-samples#500]
Running: VMware ESXi 6.0

When I try to clone a VM, I get the following:
```
Traceback (most recent call last):
  File "./clone_vm.py", line 397, in <module>
    main()
  File "./clone_vm.py", line 372, in main
    args.resource_pool, False)
  File "./clone_vm.py", line 252, in clone_vm
    WaitForTask(task)
  File "/usr/lib/python2.6/site-packages/pyvmomi-6.5.0.2017.5_1-py2.6.egg/pyVim/task.py", line 139, in WaitForTask
    raise task.info.error
pyVmomi.VmomiSupport.InvalidHostState: (vim.fault.InvalidHostState) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'The operation is not allowed in the current state of the host.',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   host = 'vim.HostSystem:host-38'
}
```
I have checked the host system to ensure that it is not in standby mode or in maintenance mode. Everything looks good on the web client. 

Any ideas of what could be causing this?

**Comment by prziborowski** [comment]
The host not being in maintenance mode and being connected should be the only things that throw InvalidHostState (source and destination).
If you have access to the vpxd.log file, it might give further insight into why the exception was thrown.

**Comment by rmdcoding** [comment]
@prziborowski I will check that file and will respond with my findings. Thanks!

**Comment by rmdcoding** [comment]
@prziborowski Nothing seems out of place in the vpxd.log file. 

I find it a little odd that cloning from the GUI produces no errors. It's only when I make an API calls (cloning or migration) that I get the mentioned errors above. I can still query VCenter and get information with no issues.

**Comment by rmdcoding** [comment]
@hartsock Any input/advice?
