### ISSUE TITLE
list_vmwaretools_status.py 

### ISSUE THREAD

**Issue by spidero** [vmware/pyvmomi-community-samples#509]
python list_vmwaretools_status.py -s XXXX -u XXX -p XXX -S
Traceback (most recent call last):
  File "list_vmwaretools_status.py", line 93, in <module>
    main()
  File "list_vmwaretools_status.py", line 70, in main
    port=args.port)
  File "/home/spider/.local/lib/python2.7/site-packages/pyVim/connect.py", line 836, in SmartConnect
    sslContext)
  File "/home/spider/.local/lib/python2.7/site-packages/pyVim/connect.py", line 718, in __FindSupportedVersion
    sslContext)
  File "/home/spider/.local/lib/python2.7/site-packages/pyVim/connect.py", line 638, in __GetServiceVersionDescription
    path + "/vimServiceVersions.xml", sslContext)
  File "/home/spider/.local/lib/python2.7/site-packages/pyVim/connect.py", line 604, in __GetElementTree
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1263, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python2.7/ssl.py", line 369, in wrap_socket
    _context=self)
  File "/usr/lib/python2.7/ssl.py", line 617, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 846, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)

i use -S option but still have SSLError

**Comment by pgbidkar** [comment]
@spidero -S is not implemented in the Sample. its issue with the sample
You can try this change in your local repo

```
import ssl
context = ssl._create_unverified_context()
  # connect to vc
    si = SmartConnect(
        host=args.host,
        user=args.user,
        pwd=args.password,
        port=args.port,
        sslContext=context)
```
