### ISSUE TITLE
OVA imported from 6.7 doesnt work with deploy_ova script

### ISSUE THREAD

**Issue by chanduusc** [vmware/pyvmomi-community-samples#540]
Imported ova from 6.7 using ovftool.

Tried deploying on to 6.7 ESXi using deploy_ova script, it fails with below error

`Traceback (most recent call last):
  File "./deploy_ova.py", line 414, in <module>
    exit(main())
  File "./deploy_ova.py", line 112, in main
    return ovf_handle.upload_disks(lease, args.host)
  File "./deploy_ova.py", line 268, in upload_disks
    self.upload_disk(fileItem, lease, host)
  File "./deploy_ova.py", line 298, in upload_disk
    urlopen(req, context=sslContext)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 405: Method Not Allowed`

**Comment by chanduusc** [comment]
When I edited ova and removed .nvram related info in ovf and mf and rebuilt ova without .nvram file, deploying works on 6.7 too

**Comment by pgbidkar** [comment]
Hi @chanduusc Thanks for providing solution. Closing the issue

Thanks

**Comment by camrossi** [comment]
Instead of patching the OVA file that seems overly convoluted I am just skipping the nvram file upload and it seems to be working fine on vc 6.7
Hope it can help other ppl as well!
```
    def upload_disks(self, lease, host):
        """
        Uploads all the disks, with a progress keep-alive.
        """
        self.lease = lease
        try:
            self.start_timer()
            for fileItem in self.spec.fileItem:
                print(fileItem)
                # Do not upload nvram files <====
                if "nvram" not in fileItem.path: # <===
                    self.upload_disk(fileItem, lease, host) 
            lease.Complete()
            print("Finished deploy successfully.")
            return 0
```
