### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'CreateScheduledTask'

### ISSUE THREAD

**Issue by zackgq2009** [vmware/pyvmomi-community-samples#605]
Run: python scheduled_poweroff.py -s 192.168.x.x -u root -p password -d "30/08/2019 20:00" -n "VM machine name"
The result is "    si.content.scheduledTaskManager.CreateScheduledTask(vm, spec)
AttributeError: 'NoneType' object has no attribute 'CreateScheduledTask'"

The si:
![20190830173112](https://user-images.githubusercontent.com/3361555/64010340-25953800-cb4c-11e9-8cde-b706117ea156.png)

**Comment by prziborowski** [comment]
It is hard to understand from the screenshot what the contents of it are.
Are you connecting directly to ESXi or going through vCenter Server?
I believe the latter doesn't support scheduling. If you are connecting to vCenter Server, Are you using SmartConnect[NoSSL] or Connect[NoSSL]?

**Comment by zackgq2009** [comment]
I got the error message:
Connected to pydev debugger (build 192.6262.63)
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2019.2.1\helpers\pydev\pydevd.py", line 2060, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm 2019.2.1\helpers\pydev\pydevd.py", line 2054, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm 2019.2.1\helpers\pydev\pydevd.py", line 1405, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "C:\Program Files\JetBrains\PyCharm 2019.2.1\helpers\pydev\pydevd.py", line 1412, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:/Users/zackg/Documents/Github/pyvmomi-community-samples/samples/scheduled_poweroff.py", line 90, in <module>
    main()
  File "C:/Users/zackg/Documents/Github/pyvmomi-community-samples/samples/scheduled_poweroff.py", line 86, in main
    si.content.scheduledTaskManager.CreateScheduledTask(vm, spec)
AttributeError: 'NoneType' object has no attribute 'CreateScheduledTask'

The 'si' object is obtained by the connect method（SmartConnectNoSSL）.

        si = connect.SmartConnectNoSSL(host=args.host,
                                       user=args.user,
                                       pwd=password,
                                       port=int(args.port))

**Comment by kumahesh** [comment]
Like @prziborowski said, 
scheduledTaskManager  is working fine when I invoked through Vcenter. When running the same sample through ESXi server, I reproduced your issue. Could you try scheduling task through vcenter?
