### ISSUE TITLE
TypeError: For "deviceName" expected type str, but got vim.Network

### ISSUE THREAD

**Issue by wolfgang1219** [vmware/pyvmomi-community-samples#624]
I want add nic to vm.
## my code：
`python3 add_nic_to_vm.py --host 192.168.1.30 --user dev --password cobbler#11 --no-ssl --vm-name master03-209 --port-group aaa`
```
#!/usr/bin/env python
from pyVmomi import vim
from pyVmomi import vmodl
from tools import tasks
from pyVim.connect import SmartConnect, SmartConnectNoSSL, Disconnect
import atexit
import argparse
import getpass

def get_args():
    parser = argparse.ArgumentParser(
        description='Arguments for talking to vCenter')

    parser.add_argument('-s', '--host',
                        required=True,
                        action='store',
                        help='vSpehre service to connect to')

    parser.add_argument('-o', '--port',
                        type=int,
                        default=443,
                        action='store',
                        help='Port to connect on')

    parser.add_argument('-u', '--user',
                        required=True,
                        action='store',
                        help='User name to use')

    parser.add_argument('-p', '--password',
                        required=False,
                        action='store',
                        help='Password to use')

    parser.add_argument('--no-ssl',
                        action='store_true',
                        help='Skip client SSL verification')

    parser.add_argument('-v', '--vm-name',
                        required=False,
                        action='store',
                        help='name of the vm')

    parser.add_argument('--uuid',
                        required=False,
                        action='store',
                        help='vmuuid of vm')

    parser.add_argument('--port-group',
                        required=True,
                        action='store',
                        help='port group to connect on')

    args = parser.parse_args()

    if not args.password:
        args.password = getpass.getpass(
            prompt='Enter password')

    return args


def get_obj(content, vimtype, name):
    obj = None
    container = content.viewManager.CreateContainerView(
        content.rootFolder, vimtype, True)
    for c in container.view:
        if c.name == name:
            obj = c
            break
    return obj


def add_nic(si, vm, network_name):
    """
    :param si: Service Instance
    :param vm: Virtual Machine Object
    :param network_name: Name of the Virtual Network
    """
    spec = vim.vm.ConfigSpec()
    nic_changes = []

    nic_spec = vim.vm.device.VirtualDeviceSpec()
    nic_spec.operation = vim.vm.device.VirtualDeviceSpec.Operation.add

    nic_spec.device = vim.vm.device.VirtualE1000()

    nic_spec.device.deviceInfo = vim.Description()
    nic_spec.device.deviceInfo.summary = 'vCenter API test'

    content = si.RetrieveContent()
    network = get_obj(content, [vim.Network], network_name)
    print("network type:", type(network))
    print("vim.OpaqueNetwork type:", type(vim.OpaqueNetwork))
    if isinstance(network, vim.OpaqueNetwork):
        nic_spec.device.backing = \
            vim.vm.device.VirtualEthernetCard.OpaqueNetworkBackingInfo()
        nic_spec.device.backing.opaqueNetworkType = \
            network.summary.opaqueNetworkType
        nic_spec.device.backing.opaqueNetworkId = \
            network.summary.opaqueNetworkId
    else:
        nic_spec.device.backing = \
            vim.vm.device.VirtualEthernetCard.NetworkBackingInfo()
        nic_spec.device.backing.useAutoDetect = False
        nic_spec.device.backing.deviceName = network

    nic_spec.device.connectable = vim.vm.device.VirtualDevice.ConnectInfo()
    nic_spec.device.connectable.startConnected = True
    nic_spec.device.connectable.allowGuestControl = True
    nic_spec.device.connectable.connected = False
    nic_spec.device.connectable.status = 'untried'
    nic_spec.device.wakeOnLanEnabled = True
    nic_spec.device.addressType = 'assigned'

    nic_changes.append(nic_spec)
    spec.deviceChange = nic_changes
    e = vm.ReconfigVM_Task(spec=spec)
    print("NIC CARD ADDED")


def main():
    args = get_args()

    # connect this thing
    serviceInstance = None
    if args.no_ssl:
        serviceInstance = SmartConnectNoSSL(
            host=args.host,
            user=args.user,
            pwd=args.password,
            port=args.port)
    else:
        serviceInstance = SmartConnect(
            host=args.host,
            user=args.user,
            pwd=args.password,
            port=args.port)
    # disconnect this thing
    atexit.register(Disconnect, serviceInstance)

    vm = None
    if args.uuid:
        search_index = serviceInstance.content.searchIndex
        vm = search_index.FindByUuid(None, args.uuid, True)
    elif args.vm_name:
        content = serviceInstance.RetrieveContent()
        vm = get_obj(content, [vim.VirtualMachine], args.vm_name)

    if vm:
        add_nic(serviceInstance, vm, args.port_group)
    else:
        print("VM not found")


# start this thing
if __name__ == "__main__":
    main()
```
## Error
```
network type: <class 'pyVmomi.VmomiSupport.vim.Network'>
vim.OpaqueNetwork type: <class 'pyVmomi.VmomiSupport.LazyType'>
Traceback (most recent call last):
  File "D:/code_file/pyvmoni-for-vsphere/pyvmomi-community-samples/samples/add_nic_to_vm.py", line 169, in <module>
    main()
  File "D:/code_file/pyvmoni-for-vsphere/pyvmomi-community-samples/samples/add_nic_to_vm.py", line 162, in main
    add_nic(serviceInstance, vm, args.port_group)
  File "D:/code_file/pyvmoni-for-vsphere/pyvmomi-community-samples/samples/add_nic_to_vm.py", line 117, in add_nic
    nic_spec.device.backing.deviceName = network
  File "D:\code_file\pyvmoni-for-vsphere\venv\lib\site-packages\pyVmomi\VmomiSupport.py", line 663, in __setattr__
    CheckField(self._GetPropertyInfo(name), val)
  File "D:\code_file\pyvmoni-for-vsphere\venv\lib\site-packages\pyVmomi\VmomiSupport.py", line 1098, in CheckField
    % (info.name, info.type.__name__, valType.__name__))
TypeError: For "deviceName" expected type str, but got vim.Network
```

Why network type not in vim.OpaqueNetwork ?

**Comment by prziborowski** [comment]
It is complaining about this part:
```
        nic_spec.device.backing.deviceName = network
```
deviceName should be a string, e.g. `network.name`

> Why network type not in vim.OpaqueNetwork ?

I'm not sure of what you mean with this question. Do you expect an OpaqueNetwork with a name of 'aaa'?

**Comment by wolfgang1219** [comment]
Yes，I  expect an OpaqueNetwork with a name of 'aaa'。

**Comment by zhlxsh** [comment]
I also encountered the same problem, the following operation can be successful
(esxi 6.7)
    nic_spec.device.backing.deviceName = network. name
