### ISSUE TITLE
list_vmwaretools_status.py Issue 2

### ISSUE THREAD

**Issue by eduardocalfaia** [vmware/pyvmomi-community-samples#636]
Hi Guys,
I got the error bellow:

Traceback (most recent call last):
  File "list_vmwaretools_status.py", line 97, in <module>
    main()
  File "list_vmwaretools_status.py", line 93, in main
    print_vmwareware_tools_status(vm_obj)
  File "list_vmwaretools_status.py", line 62, in print_vmwareware_tools_status
    vm.guest.toolsVersionStatus2))
TypeError: unsupported format string passed to NoneType.__format__

may you help me?

Thanks

**Comment by eduardocalfaia** [comment]
Hi guys
I have found something about that. The error happens when the result is a template.

**Comment by eduardocalfaia** [comment]
Hi guy 
I was wrong the problem is the string like that  Template-win-srv-2012-r2-std

**Comment by eduardocalfaia** [comment]
I've checked better and I have found a template with the Version equal Null and that is the issue.

**Comment by eduardocalfaia** [comment]
Hi guys,
I have fixed that

def print_vmwareware_tools_status(vm):
    print(_columns_four.format(vm.name,
                               vm.guest.toolsRunningStatus,
                               **str(vm.guest.toolsVersion)**,
                               vm.guest.toolsVersionStatus2))
